### ISSUE TITLE
enhancement: Usage section of the readme

### ISSUE THREAD

**Issue by SusheelThapa** [sneha-4-22/CryptoMate#2]
As I seen that you have added  `requirements.txt` files in the project, you can replace the step 2 with `pip install -r requirements.txt`.

Also, it would be great if you included an step to create a virtual enviroment before installing the python packages like `python -m venv venv`

Moreover, you can use `pip freeze > requirements.txt` command to generate the `requirements.txt` files as this will ensure the version that you have used in the developement of the project match with the version other people with be running your project.

Sample of `requirements.txt` generated using above command.

```bash
taipy==3.1.0
taipy-config==3.1.0
taipy-core==3.1.0
taipy-gui==3.1.0
taipy-rest==3.1.0
taipy-templates==3.1.0
```

Addtionally, you can link the dependancies to their homepage as [Taipy](https://www.taipy.io/)

In the about section of the project you have included emoji, it would be nice if you could write short description about the project as this help to index the project.

![image](https://github.com/sneha-4-22/CryptoMate/assets/83917129/8e51ca55-2acb-44e9-ac01-b0d5ad12e613)

**Comment by SusheelThapa** [comment]
Also, I have some unnecessary folder in the project like `.data` `__pycache__`,etc

You can add a `.gitignore` files to exclude those folder.

**Comment by sneha-4-22** [comment]
Done👩🏻‍💻
